### ISSUE TITLE
json address field has incorrect data type

### ISSUE THREAD

**Issue by philipyoo** [sfbrigade/sfsbook#131]
Some address fields in the refguide.json filed contain an integer type rather than a string. In the search field on the site, when looking for "Child Sexual Abuse", it returns a 404 error.

What follows is from the server log:

```
    4. 92dfec37-76ee-45f0-be04-1b47540cb981 (0.947790)
    email
        
    address
        83
    name
        Child Help USA
    categories
        Child Sexual Abuse Hotlines
    description
        National Child Abuse Hotline
    services
        24 Hr. crisis-line, counseling information and referrals
    website
        www.childhelp.org
```

```
2017/04/05 20:43:03 http2: panic serving [::1]:58473: interface conversion: interface {} is float64, not string
goroutine 73 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc42000e018, 0xc420399faf, 0xc4200f4380)
    /usr/local/Cellar/go/1.8/libexec/src/net/http/h2_bundle.go:4592 +0x190
panic(0x14b4100, 0xc4202d1640)
    /usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2cf
github.com/sfbrigade/sfsbook/dba.(*QueryResultsGenerator).ForRequest(0xc42016a7f0, 0x152c160, 0xc42000a700, 0xf8, 0xc42000a700)
    /Users/peter/go/src/github.com/sfbrigade/sfsbook/dba/query_generator.go:127 +0xe88
```

**Comment by techieshark** [comment]
Fixed by #133
